### ISSUE TITLE
Tracker - v1.0.0-M1

### ISSUE THREAD

**Issue by HunHage** [HunHage/Audy#1]
Since I will have to step away from this for a moment (again) I'll be leaving my to-do list here for the first milestone towards v1.0.0, where most internal systems should be established and working as well as data storage.

Features are only marked as implemented once they are merged with the master branch.

### **Internal Systems:**
- [x] Error Handling and Logging
- [x] Tree Based Command Parser
- [x] SQL Database Management/Interface
- [x] Scheduler
- [x] Argument Parser

### **Configuration:**
- [x] Custom Guild Prefixes
- [x] Configurable Archive Retention Time and Scanning Time
- [x] Turn Off SQL Features
- [x] Scheduler Reminder Limits

### **Commands:**
- [x] Help
- [x] Guild Prefix Configuration
**Information Commands for:**
- [x] User
- [x] Role
- [x] Channel
- [x] Guild
**Reminders:**
- [x] remind me
    ~~remind here~~
- [x] remind list
- [x] remind delete
**Archived Data:**
- [x] Retrieve Archived Messages
- [x] Retrieve Archived Users
- [x] Retrieve Archived Members

### **Archival:**
- [x] Archive Files
- [x] Archive Messages
- [x] Archive Message Edits/Deletions
- [x] Archive User Profiles
- [x] Archive Member Nicknames

**Comment by HunHage** [comment]
Finally, now to create a new list for everything added to Discord in the last 7 months
