### ISSUE TITLE
Tracker v1.0.0-M2

### ISSUE THREAD

**Issue by HunHage** [HunHage/Audy#4]
# Code Cleanup
- [ ] Add comments to missing areas.
- [ ] Fix Archive logging to not improperly block

# Code Consistency
- [ ] Add logging to missing areas.
- [ ] Only use reactor loggers instead of SLF4J loggers.
